#!/usr/bin/env bash

#bin=$(which "$0")
#bin=$(dirname "$bin")
#bin=$(cd "$bin"; pwd)

pid_file=./logagent.pid
if [ -f "$pid_file" ]; then
    echo "LogAgent pid file exists. pid: `cat $pid_file`"
    exit 2
fi

#nohup java -Xmx256M -jar ./logAgent-1.0.jar --pid_file $pid_file > /dev/null 2>&1 &
nohup java -Xms256M -Xmx512M -jar ./logAgent-1.0.jar >> nohup.out 2>&1 & echo $! > ./logagent.pid

for i in `seq 1 5`
do
    if [ -f "$pid_file" ]; then
        echo "LogAgent started."
        exit 0
    fi
    sleep 1
done

echo "LogAgent start failed."
exit 1

