copy FsSoloLoader.exe game_entry.exe
copy FsSoloLoader.pdb game_entry.pdb
copy FsSoloLoader.map game_entry.map
copy FsSoloLoader.exe game_lister.exe
copy FsSoloLoader.pdb game_lister.pdb
copy FsSoloLoader.map game_lister.map
copy FsSoloLoader.exe game_log.exe
copy FsSoloLoader.pdb game_log.pdb
copy FsSoloLoader.map game_log.map
copy FsSoloLoader.exe game_member.exe
copy FsSoloLoader.pdb game_member.pdb
copy FsSoloLoader.map game_member.map
copy FsSoloLoader.exe game_public.exe
copy FsSoloLoader.pdb game_public.pdb
copy FsSoloLoader.map game_public.map
copy FsSoloLoader.exe game_store.exe
copy FsSoloLoader.pdb game_store.pdb
copy FsSoloLoader.map game_store.map
copy FsSoloLoader.exe game_world.exe
copy FsSoloLoader.pdb game_world.pdb
copy FsSoloLoader.map game_world.map
copy FsSoloLoader.exe game_unite.exe
copy FsSoloLoader.pdb game_unite.pdb
copy FsSoloLoader.map game_unite.map
copy FsSoloLoader.exe game_entry1.exe
copy FsSoloLoader.pdb game_entry1.pdb
copy FsSoloLoader.map game_entry1.map
copy FsSoloLoader.exe game_logincache.exe
copy FsSoloLoader.pdb game_logincache.pdb
copy FsSoloLoader.map game_logincache.map
copy FsSoloLoader.exe game_charge.exe
copy FsSoloLoader.pdb game_charge.pdb
copy FsSoloLoader.map game_charge.map
copy FsSoloLoader.exe game_gmcc.exe
copy FsSoloLoader.pdb game_gmcc.pdb
copy FsSoloLoader.map game_gmcc.map

copy FsSoloLoader.exe game_snsmanager.exe
copy FsSoloLoader.pdb game_snsmanager.pdb
copy FsSoloLoader.map game_snsmanager.map
copy FsSoloLoader.exe game_snsstore.exe
copy FsSoloLoader.pdb game_snsstore.pdb
copy FsSoloLoader.map game_snsstore.map
copy FsSoloLoader.exe game_sns.exe
copy FsSoloLoader.pdb game_sns.pdb
copy FsSoloLoader.map game_sns.map

copy FsSoloLoader.exe game_platform.exe
copy FsSoloLoader.pdb game_platform.pdb
copy FsSoloLoader.map game_platform.map
copy FsSoloLoader.exe game_room.exe
copy FsSoloLoader.pdb game_room.pdb
copy FsSoloLoader.map game_room.map

copy FsSoloLoader.exe game_member1.exe
copy FsSoloLoader.pdb game_member1.pdb
copy FsSoloLoader.map game_member1.map
copy FsSoloLoader.exe game_member2.exe
copy FsSoloLoader.pdb game_member2.pdb
copy FsSoloLoader.map game_member2.map
copy FsSoloLoader.exe game_member3.exe
copy FsSoloLoader.pdb game_member3.pdb
copy FsSoloLoader.map game_member3.map
copy FsSoloLoader.exe game_member4.exe
copy FsSoloLoader.pdb game_member4.pdb
copy FsSoloLoader.map game_member4.map
copy FsSoloLoader.exe game_member5.exe
copy FsSoloLoader.pdb game_member5.pdb
copy FsSoloLoader.map game_member5.map
copy FsSoloLoader.exe game_member6.exe
copy FsSoloLoader.pdb game_member6.pdb
copy FsSoloLoader.map game_member6.map
copy FsSoloLoader.exe game_member7.exe
copy FsSoloLoader.pdb game_member7.pdb
copy FsSoloLoader.map game_member7.map