#ifndef __ENVIR_DEFINE__
#define __ENVIR_DEFINE__

#include "enum.h"
/* -----------------------------------------------------
 * 常量值类型
 * ---------------------------------------------------*/
enum EnvirValueTypes
{
	ENV_VALUE_NONE = -1,
	ENV_VALUE_PLAYER_WALK_STEP_DEFAULT,			// 玩家行走高度差
	ENV_VALUE_NPC_WALK_STEP_DEFAULT,			// NPC行走高度差
	ENV_VALUE_CHECK_SYNC_RANGE,					// 检查移动同步误差
	ENV_VALUE_DEFAULT_RUN_SPEED,				// 玩家的移动速度
	ENV_VALUE_CHECK_DIST_TOTAL_WARNING,			// 位置校正警告值
	ENV_VALUE_CHECK_DIST_TOTAL_MAX,				// 位置校正最大
	ENV_VALUE_HEART_BEAT_WARNING,				// 心跳警告值
	ENV_VALUE_HEART_BEAT_MAX,					// 心跳最大
	ENV_VALUE_GUIDE_SCENE_BRON_POS,				// 引导场景pos
	ENV_VALUE_RESET_MAX_HP_TIME,				// 重新设置MaxHP时间
	ENV_VALUE_NOMAL_FRIEND_INTIMACY_MAX,		// 普通好友亲密度等级最大值
	ENV_VALUE_SWORN_FRIEND_INTIMACY_MAX,		// 结义好友亲密度等级最大值
	ENV_VALUE_FRIEND_RECOMM_LEVEL_DIFF,			// 推荐好友等级差
	ENV_VALUE_FRIEND_RECOMM_LEVEL_INTVAL,		// 推荐好友等级段
	ENV_VALUE_SWORN_NEED_ITEM1,					// 结义需求道具
	ENV_VALUE_SWORN_NEED_ITEM2,					// 结缘需求道具
	ENV_VALUE_FLOWER_TO_CHARM_UNIT,				// 好友送花转换成魅力单位值
	ENV_VALUE_PLAYER_KILL_HATREDT,				// 玩家被击杀的仇恨值
	ENV_VALUE_DEL_SWORN_NEEN_COPPER,			// 取消结缘对象需要铜钱
	ENV_VALUE_SWORN_SKI_AID_CD,					// 结义召唤cd(单位秒)
	ENV_VALUE_NEARBY_PLAYER_DISTANCE,			// 附近玩家扫描距离（不能太大)
	ENV_VALUE_FLOWER_TO_INTIMACY_UNIT,			// 好友送花转换成亲密度单位值
	ENV_VALUE_TEAM_RECOMMAND_LVDIFF,			// 组队推荐等级差
	ENV_VALUE_TEAM_RECOMMAND_NUM,				// 组队推荐人数
	ENV_VALUE_LEAVE_FIGHT_TIME,					// 脱离战斗时间  

	// hp mp回复相关常量
	ENV_VALUE_HP_RESTORE_TIME,					// 恢复HP时间间隔
	ENV_VALUE_MP_RESTORE_TIME,					// 恢复MP时间间隔
	ENV_VALUE_RESTORE_HP,						// 正常时恢复HP值
	ENV_VALUE_FIGHT_RESTORE_MP,					// 战斗时恢复MP值
	ENV_VALUE_NORMAL_RESTORE_MP,				// 正常时恢复MP值

	ENV_VALUE_PLAYER_CREATE_REWARD,				// 玩家出生时的物品
	ENV_VALUE_BAPTISE_LIMIT_STR_LVL,			// 洗练的强化等级限制
	ENV_VALUE_BAPTISE_LIMIT_COLOR,				// 洗练的品质限制
	ENV_VALUE_BAPTISE_PROP_LOCK_CAPITAL,		// 洗练属性锁定花费货币类型
	ENV_VALUE_BAPTISE_PROP_LOCK_CAPITAL_NUM,	// 洗练属性锁定花费货币数量
	ENV_VALUE_SMELT_MAX_NUM,					// 每次熔炼的物品最大数量
	ENV_VALUE_SMELT_VALUE_FORMULA,				// 熔炼值输出公式
	ENV_VALUE_STRENGTHEN_MAX_LEVEL,				// 强化最大等级
	ENV_VALUE_STRENGTHEN_AUTO_COUNT,			// 一键强化最大次数
	ENV_VALUE_CHANGE_ANNOUNCEMENT,				// 修改组织公告花费
	ENV_VALUE_ADD_GUILD_CD,						// 退出公会(被踢出)公会惩罚cd-单位分钟
	ENV_VALUE_FIRST_RIDE,						// 坐骑功能开启送到坐骑ID
	ENV_VALUE_CREATE_GUILD_GOLD,				// 创建公会花费
	ENV_VALUE_MAX_FIRE_NUM,						// 会长每天最大踢人数
	ENV_VALUE_ASSIST_ATTACK_DISTANCE,			// 助攻距离
	ENV_VALUE_TEAMOFFER_LIMIT_PEOPLE,			// 缉盗组队最小人数
	ENV_VALUE_TEAMOFFER_ENTRY_NPC,				// 缉盗入口Npc
	ENV_VALUE_TEAMOFFER_TIME,					// 缉盗时长（分钟）

	ENVIR_VALUE_MAX
};


ENUM_TO_STRING_EX(EnvirValueTypes, ENVIR_VALUE_MAX, 
					ENUM_ITEM_STR(ENV_VALUE_PLAYER_WALK_STEP_DEFAULT)
					ENUM_ITEM_STR(ENV_VALUE_NPC_WALK_STEP_DEFAULT)
					ENUM_ITEM_STR(ENV_VALUE_CHECK_SYNC_RANGE)
					ENUM_ITEM_STR(ENV_VALUE_DEFAULT_RUN_SPEED)
					ENUM_ITEM_STR(ENV_VALUE_CHECK_DIST_TOTAL_WARNING)
					ENUM_ITEM_STR(ENV_VALUE_CHECK_DIST_TOTAL_MAX)
					ENUM_ITEM_STR(ENV_VALUE_HEART_BEAT_WARNING)
					ENUM_ITEM_STR(ENV_VALUE_HEART_BEAT_MAX)
					ENUM_ITEM_STR(ENV_VALUE_GUIDE_SCENE_BRON_POS)
					ENUM_ITEM_STR(ENV_VALUE_RESET_MAX_HP_TIME)
					ENUM_ITEM_STR(ENV_VALUE_NOMAL_FRIEND_INTIMACY_MAX)
					ENUM_ITEM_STR(ENV_VALUE_SWORN_FRIEND_INTIMACY_MAX)
					ENUM_ITEM_STR(ENV_VALUE_FRIEND_RECOMM_LEVEL_DIFF)
					ENUM_ITEM_STR(ENV_VALUE_FRIEND_RECOMM_LEVEL_INTVAL)
					ENUM_ITEM_STR(ENV_VALUE_SWORN_NEED_ITEM1)
					ENUM_ITEM_STR(ENV_VALUE_SWORN_NEED_ITEM2)
					ENUM_ITEM_STR(ENV_VALUE_FLOWER_TO_CHARM_UNIT)
					ENUM_ITEM_STR(ENV_VALUE_PLAYER_KILL_HATREDT)
					ENUM_ITEM_STR(ENV_VALUE_DEL_SWORN_NEEN_COPPER)
					ENUM_ITEM_STR(ENV_VALUE_SWORN_SKI_AID_CD)
					ENUM_ITEM_STR(ENV_VALUE_NEARBY_PLAYER_DISTANCE)
					ENUM_ITEM_STR(ENV_VALUE_FLOWER_TO_INTIMACY_UNIT)
					ENUM_ITEM_STR(ENV_VALUE_TEAM_RECOMMAND_LVDIFF)
					ENUM_ITEM_STR(ENV_VALUE_TEAM_RECOMMAND_NUM)
					ENUM_ITEM_STR(ENV_VALUE_LEAVE_FIGHT_TIME)

					ENUM_ITEM_STR(ENV_VALUE_HP_RESTORE_TIME)
					ENUM_ITEM_STR(ENV_VALUE_MP_RESTORE_TIME)
					ENUM_ITEM_STR(ENV_VALUE_RESTORE_HP)
					ENUM_ITEM_STR(ENV_VALUE_FIGHT_RESTORE_MP)
					ENUM_ITEM_STR(ENV_VALUE_NORMAL_RESTORE_MP)

					ENUM_ITEM_STR(ENV_VALUE_PLAYER_CREATE_REWARD)
					ENUM_ITEM_STR(ENV_VALUE_BAPTISE_LIMIT_STR_LVL)
					ENUM_ITEM_STR(ENV_VALUE_BAPTISE_LIMIT_COLOR)
					ENUM_ITEM_STR(ENV_VALUE_BAPTISE_PROP_LOCK_CAPITAL)
					ENUM_ITEM_STR(ENV_VALUE_BAPTISE_PROP_LOCK_CAPITAL_NUM)
					ENUM_ITEM_STR(ENV_VALUE_SMELT_MAX_NUM)
					ENUM_ITEM_STR(ENV_VALUE_SMELT_VALUE_FORMULA)
					ENUM_ITEM_STR(ENV_VALUE_STRENGTHEN_MAX_LEVEL)
					ENUM_ITEM_STR(ENV_VALUE_STRENGTHEN_AUTO_COUNT)
					ENUM_ITEM_STR(ENV_VALUE_CHANGE_ANNOUNCEMENT)
					ENUM_ITEM_STR(ENV_VALUE_ADD_GUILD_CD)
					ENUM_ITEM_STR(ENV_VALUE_FIRST_RIDE)
					ENUM_ITEM_STR(ENV_VALUE_CREATE_GUILD_GOLD)
					ENUM_ITEM_STR(ENV_VALUE_MAX_FIRE_NUM)
					ENUM_ITEM_STR(ENV_VALUE_ASSIST_ATTACK_DISTANCE)
					ENUM_ITEM_STR(ENV_VALUE_TEAMOFFER_LIMIT_PEOPLE)
					ENUM_ITEM_STR(ENV_VALUE_TEAMOFFER_ENTRY_NPC)
					ENUM_ITEM_STR(ENV_VALUE_TEAMOFFER_TIME)
					);
#endif