/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef exception_CONSTANTS_H
#define exception_CONSTANTS_H

#include "exception_types.h"



class exceptionConstants {
 public:
  exceptionConstants();

};

extern const exceptionConstants g_exception_constants;



#endif
