/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef model_CONSTANTS_H
#define model_CONSTANTS_H

#include "model_types.h"



class modelConstants {
 public:
  modelConstants();

};

extern const modelConstants g_model_constants;



#endif
